# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126
os_type: centos

tasks:
- install:
- ceph: {cluster: c1}
- ceph: {cluster: c2}
- rgw:
    c1.client.0:
      valgrind: [--tool=memcheck]
    c1.client.1:
      valgrind: [--tool=memcheck]
    c2.client.0:
      valgrind: [--tool=memcheck]
    c2.client.1:
      valgrind: [--tool=memcheck]
- netem:
    clients: [c1.client.0]
    dst_client: [c2.client.0]
    delay_range: [10ms, 20ms]
- rgw-multisite:
- rgw-multisite-tests:
    config:
      reconfigure_delay: 60
